### ISSUE TITLE
First code was running fine but after 1 day it will show me error and not converting Currency (waiting for solution)

### ISSUE THREAD

**Issue by maliktariq49** [hamzakhurshid12/forex_conversion#1]
E/flutter (12420): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)
E/flutter (12420): 
E/flutter (12420): ^
E/flutter (12420): 
E/flutter (12420): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
E/flutter (12420): #1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
E/flutter (12420): #2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
E/flutter (12420): #3      JsonDecoder.convert (dart:convert/json.dart:612:36)
E/flutter (12420): #4      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter (12420): #5      Forex._fetchCurrencies (package:forex_conversion/forex_conversion.dart:14:14)
E/flutter (12420): <asynchronous suspension>
E/flutter (12420): #6      Forex.getAllCurrenciesPrices (package:forex_conversion/forex_conversion.dart:40:5)
E/flutter (12420): <asynchronous suspension>

**Comment by hamzakhurshid12** [comment]
@maliktariq49 there was an issue with the underlying API we use from convertmymoney.com.
It has been fixed at their end, so the plugin works great now!
