### ISSUE TITLE
When converting from VND to USD, the result returns 0.0

### ISSUE THREAD

**Issue by minhto2811** [hamzakhurshid12/forex_conversion#4]
![image](https://github.com/user-attachments/assets/5f9b902b-ee60-4fbe-a72b-380c072de8d4)

**Comment by hamzakhurshid12** [comment]
@minhto2811 I cannot recreate this issue. Can you please share the complete code including the initialisation steps?

**Comment by minhto2811** [comment]
I'm sorry, I reviewed my code and I realized the problem is not with the library. day
